### ISSUE TITLE
Upgrading to AngularFire2 4.0

### ISSUE THREAD

**Issue by nrodriguezm** [rodrigoreal/ionic2-angularfire-login#29]
Do you plan on updating demo to use the new AngularFire2 release?

https://github.com/angular/angularfire2/blob/master/docs/version-4-upgrade.md

Great work, thanks.

**Comment by rodrigoreal** [comment]
Yeah, i do, and update the ionic to 3.1 or the latest one.
I'll prob do it next week.

**Comment by juntaforce** [comment]
Come on Rodrigo we are waiting for you 🥇

**Comment by nrodriguezm** [comment]
Got impatient and made one!  😀

https://github.com/nrodriguezm/ionic-login-firebase-email-social


-
Nicolás Rodríguez Medeyros

**Comment by juntaforce** [comment]
Thanks for your effort Nicolas. I would try your solution ASAP.

**Comment by nrodriguezm** [comment]
Tell me what you think. I will add g+ soon.

**Comment by nrodriguezm** [comment]
Just uploaded Google+ Login with instructions. 

I will translate instructions later to English, adding it was smooth with Firebase+AngularFire2 integration.

**Comment by juntaforce** [comment]
Hi @nrodriguezm ,
I upgraded my projects with your repository without cordova Facebook and Google native plugins.
Because there is no time but when I upgrade the native plugins I will inform you in your repository...
As you said if you translate to English it would be spectacular :)  
But excellent, thanks again for your effort  👍

**Comment by rodrigoreal** [comment]
Sorry guys if it took this long for me to upgrade the project, i was really busy.
I updated the project to Ionic 3.6, Angularfire 4.0 and i'm also using firebase functions.
